spring:
  application:
    name: starly-backend
  mongodb:
    database: starly-dev
  data:
    mongodb:
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379

jwt:
  secret:
  access-token-expiration: 900000      # 15분 (ms)
  refresh-token-expiration: 604800000  # 7일 (ms)
  refresh-token-cookie-max-age: 604800 # 7일 (s)